**Sobre a biblioteca NumPy**

> É uma biblioteca utilizada principalmente para o uso de arrays e matrizes, onde se aplica operações matemáticas e estatísticas. É excelente para lidar com grandes quantidades de informações e dados.

> Começaremos importando a biblioteca que já é nativa da linguaguem Python

In [2]:
import numpy as np

**O que é um Array?**

>  É uma estrutura de dados que armazena uma coleção de elementos de forma ordenada. Cada elemento é acessado por um índice, que é um número inteiro que representa a posição do elemento na lista.

> O índice do primeiro elemento é 0, o índice do segundo elemento é 1, e assim por diante 


In [3]:
#Para criar uma array, utilize:
    
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

> No caso acima, a lista [1, 2, 3, 4, 5] se torna uma array. 

>Então, qual é a diferença entre uma array e uma lista?

>*Um array é uma estrutura de dados que armazena elementos do MESMO tipo de dados em uma sequência contínua de memória. Já uma lista, é uma estrutura encadeada com dados em nós, onde cada nó contem um valor, e o ponteiro passa para o próximo da lista. Ao meu entender (e posso estar errado), um array é um pacote de informações, alocado em um espaço na memória, todo junto, em constraste com a lista, que cada item da lista é um valor guardado em um local na memória.*
> *A principal diferença é que arrays são mais eficientes em termos de memória e desempenho para operações matemáticas e estatísticas, enquanto listas são mais flexíveis e podem armazenar diferentes tipos de dados.*


Podemos ter arrays em duas dimensões (matriz).

In [7]:
# Vamos utilizar uma lista de lista para criar uma matriz

lista = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
# Para criar uma matriz, utilize np.array e passe a lista de lista como argumento

np.array(lista)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Método arange()

> Podemos criar uma array sequenciada utilizando esse método.

In [11]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(0,100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

> O método arange permite utilizar *steps* como no exemplo abaixo:

In [13]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

> Observe que o arange cria um array de 0 até 10, com passo 2. Ou seja, ele pula de 2 em 2.

> Para criar uma matriz utilizando arange, podemos utilizar também o reshape()

Método reshape()

In [15]:
np.arange(0,10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

> Perceba que o método reshape(2,5) transforma a array de 10 elementos em uma matriz de 2 linhas e 5 colunas.

Métodos zeros() e ones()

> Para criar uma array com 0 e/ou 1, teremos que utilizar os métodos do titulo. Veja o exemplo abaixo:

In [16]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [18]:
# Para criar uma matriz com zeros, utilize np.zeros e passe o número de linhas e colunas como argumento

np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

> O mesmo procedimento pode ser utilizado para o one()

In [20]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [21]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

> Há outros métodos para criar matrizes.

Método eye()

> Esse método se diferencia, pois cria uma matriz identidade.

In [22]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Método linspace()

> O linspace é uma função que cria uma lista de números igualmente espaçados. Você escolhe o primeiro e o último número, e a função divide o intervalo entre eles em partes iguais.

In [26]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [28]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [29]:
np.linspace(0,10,9)

array([ 0.  ,  1.25,  2.5 ,  3.75,  5.  ,  6.25,  7.5 ,  8.75, 10.  ])

In [38]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

Método random.rand() e random.randn()

> Há também um método de criar uma distribuição aleátoria de números dentro de uma array. Estas são chamadas de *distribuição uniforme*.

In [30]:
np.random.rand(5)

array([0.3352333 , 0.27916677, 0.20391196, 0.37875207, 0.42076937])

In [32]:
np.random.rand(5,5)

array([[0.75645914, 0.83720253, 0.90892246, 0.95820315, 0.19291585],
       [0.29144139, 0.84174727, 0.52400836, 0.38525076, 0.77684688],
       [0.1602426 , 0.71636808, 0.88059322, 0.8160973 , 0.74342392],
       [0.49004277, 0.78880798, 0.61852837, 0.87228314, 0.65338219],
       [0.76388687, 0.77863731, 0.60506226, 0.48035491, 0.22903347]])

In [34]:
np.random.rand(3,3,3)

array([[[0.47014366, 0.70602953, 0.45272607],
        [0.2980212 , 0.07521125, 0.02836109],
        [0.60709839, 0.0674918 , 0.11666518]],

       [[0.38625083, 0.61100527, 0.6823964 ],
        [0.77542014, 0.72358518, 0.78733622],
        [0.76791329, 0.01678574, 0.63932514]],

       [[0.98661171, 0.62579582, 0.10747083],
        [0.51332926, 0.3392328 , 0.04762154],
        [0.94930414, 0.21855217, 0.55343027]]])

> Para criar uma array aleatória com a *distribuição normal* utilizamos o método randn()

In [35]:
np.random.randn(5)

array([ 0.63257946,  0.76112127, -0.20186969,  0.24115958,  1.83033291])

In [36]:
np.random.randn(5,5)

array([[ 0.18661411,  0.10245873, -0.07734393,  0.0907463 , -0.96710877],
       [-0.85327435, -1.32119932, -0.0596007 ,  1.00436844,  0.46607677],
       [-0.40806499, -0.40310021, -0.74243149, -0.17607814, -2.67925391],
       [ 0.85973147, -0.43642781,  0.73223789, -0.87538077,  0.91241313],
       [ 0.70253697,  0.98366249, -0.08278629, -2.84233053, -1.21311763]])

In [37]:
np.random.randn(3,3,3)

array([[[-0.17366846, -2.56265651, -0.24471951],
        [ 0.15274321, -0.66587556,  0.98100298],
        [-2.15788859, -1.88231643,  0.8845547 ]],

       [[ 0.2924278 ,  1.6010006 , -1.54893044],
        [-1.4830714 , -0.37227215,  1.11886717],
        [-0.28134331, -2.32753008, -0.56825267]],

       [[-0.62876871,  1.24845617,  0.05702891],
        [-1.29905163, -1.30139517, -0.64785286],
        [-0.09671949,  0.70142098,  1.19013693]]])

> Da mesma maneira, podemos utilizar um outro método para trazer números inteiros para nossa matrizes.

Método randint()

> Funciona da mesma maneira que um rand() ou randn()

In [61]:
np.random.randint(0,100)

83

In [62]:
np.random.randint(0,100,10)

array([74, 56, 96, 22, 34, 90, 87, 57, 95, 37])

> O professor salienta que é interessante criar matrizes com números inteiros utilizando o randint() com o reshape()

In [70]:
np.random.randint(0,100,10).reshape(2,5)

array([[49, 11, 54, 94, 12],
       [81, 66, 17, 27,  7]])

> Outra questão que vale a pena entender, o reshape() transforma um array em uma matriz, e para conferir se o que voce tem é ou um array ou uma matriz, utilize o shape ''sem aspas'' mesmo

In [73]:
arr = np.random.rand(25)

In [74]:
arr

array([0.92295641, 0.3384424 , 0.31475027, 0.89470781, 0.65206769,
       0.75522762, 0.35056353, 0.06465662, 0.86673626, 0.15594538,
       0.75187782, 0.68441868, 0.01839129, 0.51441791, 0.02499234,
       0.25450421, 0.23025485, 0.27502786, 0.82008273, 0.05070279,
       0.93994801, 0.59875031, 0.55401907, 0.69536624, 0.49871685])

In [75]:
arr.shape

(25,)

> Note que ele retorna nossa array, dizendo que ela possui 25 valores. Para transformar em uma matriz, utilizaremos o reshape()

In [77]:
arr = arr.reshape(5,5)

In [78]:
arr

array([[0.92295641, 0.3384424 , 0.31475027, 0.89470781, 0.65206769],
       [0.75522762, 0.35056353, 0.06465662, 0.86673626, 0.15594538],
       [0.75187782, 0.68441868, 0.01839129, 0.51441791, 0.02499234],
       [0.25450421, 0.23025485, 0.27502786, 0.82008273, 0.05070279],
       [0.93994801, 0.59875031, 0.55401907, 0.69536624, 0.49871685]])

> *Interessante ver que na array, os valores terminam com "])" e em uma matriz, termina com "]])"*

max(), min(), argmax() e argmin()

> Há uma maneira de procurar por argumentos dentro das matrizes ou arrays.

>max() encontrará o valor máximo de uma matriz

>min() encontrará o valor mínimo de uma matriz

>argmax() trará a posição do valor máximo dentro da matriz (lembrando que a posição conta a partir do 0)

>argmin() trará a posição do valor mínimo dentro da matriz

In [79]:
arr

array([[0.92295641, 0.3384424 , 0.31475027, 0.89470781, 0.65206769],
       [0.75522762, 0.35056353, 0.06465662, 0.86673626, 0.15594538],
       [0.75187782, 0.68441868, 0.01839129, 0.51441791, 0.02499234],
       [0.25450421, 0.23025485, 0.27502786, 0.82008273, 0.05070279],
       [0.93994801, 0.59875031, 0.55401907, 0.69536624, 0.49871685]])

In [80]:
arr.max()

0.9399480097099472

In [81]:
arr.min()

0.018391294612110753

In [83]:
arr.argmax()

20

In [84]:
arr.argmin()

12