**Sobre a biblioteca NumPy**

> É uma biblioteca utilizada principalmente para o uso de arrays e matrizes, onde se aplica operações matemáticas e estatísticas. É excelente para lidar com grandes quantidades de informações e dados.

> Começaremos importando a biblioteca que já é nativa da linguaguem Python

In [2]:
import numpy as np

**O que é um Array?**

>  É uma estrutura de dados que armazena uma coleção de elementos de forma ordenada. Cada elemento é acessado por um índice, que é um número inteiro que representa a posição do elemento na lista.

> O índice do primeiro elemento é 0, o índice do segundo elemento é 1, e assim por diante 


In [3]:
#Para criar uma array, utilize:
    
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

> No caso acima, a lista [1, 2, 3, 4, 5] se torna uma array. 

>Então, qual é a diferença entre uma array e uma lista?

>*Um array é uma estrutura de dados que armazena elementos do MESMO tipo de dados em uma sequência contínua de memória. Já uma lista, é uma estrutura encadeada com dados em nós, onde cada nó contem um valor, e o ponteiro passa para o próximo da lista. Ao meu entender (e posso estar errado), um array é um pacote de informações, alocado em um espaço na memória, todo junto, em constraste com a lista, que cada item da lista é um valor guardado em um local na memória.*
> *A principal diferença é que arrays são mais eficientes em termos de memória e desempenho para operações matemáticas e estatísticas, enquanto listas são mais flexíveis e podem armazenar diferentes tipos de dados.*


Podemos ter arrays em duas dimensões (matriz).

In [7]:
# Vamos utilizar uma lista de lista para criar uma matriz

lista = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
# Para criar uma matriz, utilize np.array e passe a lista de lista como argumento

np.array(lista)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Método arange()

> Podemos criar uma array sequenciada utilizando esse método.

In [11]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(0,100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

> O método arange permite utilizar *steps* como no exemplo abaixo:

In [13]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

> Observe que o arange cria um array de 0 até 10, com passo 2. Ou seja, ele pula de 2 em 2.

> Para criar uma matriz utilizando arange, podemos utilizar também o reshape()

Método reshape()

In [15]:
np.arange(0,10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

> Perceba que o método reshape(2,5) transforma a array de 10 elementos em uma matriz de 2 linhas e 5 colunas.

Métodos zeros() e ones()

> Para criar uma array com 0 e/ou 1, teremos que utilizar os métodos do titulo. Veja o exemplo abaixo:

In [16]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [18]:
# Para criar uma matriz com zeros, utilize np.zeros e passe o número de linhas e colunas como argumento

np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

> O mesmo procedimento pode ser utilizado para o one()

In [20]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [21]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])